export enum ECardType {
  Attack = "Attack",
  Skill = "Skill",
  Other = "Other",
}

export enum EElement {
  Pyro = "Pyro",
  Hydro = "Hydro",
  Cryo = "Cryo",
  Electro = "Electro",
  Anemo = "Anemo",
  Geo = "Geo",
  Dendro = "Dendro",
}

export enum ECharacter {
  Aether = "Aether",
  Albedo = "Albedo",
  Amber = "Amber",
  Barbara = "Barbara",
  Beidou = "Beidou",
  Bennett = "Bennett",
  ChongYun = "ChongYun",
  Diluc = "Diluc",
  Diona = "Diona",
  Eula = "Eula",
  Fischl = "Fischl",
  Ganyu = "Ganyu",
  HuTao = "HuTao",
  Jean = "Jean",
  Kaeya = "Kaeya",
  Kazuha = "Kazuha",
  KeQing = "KeQing",
  Klee = "Klee",
  Lisa = "Lisa",
  Lumine = "Lumine",
  Mona = "Mona",
  NingGuang = "NingGuang",
  Noelle = "Noelle",
  QiQi = "QiQi",
  Raiden = "Raiden",
  Razor = "Razor",
  Rosaria = "Rosaria",
  Sucrose = "Sucrose",
  Tartaglia = "Tartaglia",
  Venti = "Venti",
  XiangLing = "XiangLing",
  Xiao = "Xiao",
  XingQiu = "XingQiu",
  Xinyan = "Xinyan",
  Yanfei = "Yanfei",
  Yoimiya = "Yoimiya",
  ZhongLi = "ZhongLi",
}

export enum ECard {
  // Aether
  StarfellSword = "StarfellSword",
  StarfellSwordPlus = "StarfellSwordPlus",
  ForeignRockblade = "ForeignRockblade",
  ForeignRockbladePlus = "ForeignRockbladePlus",
  // Albedo
  WeissBladework = "WeissBladework",
  WeissBladeworkPlus = "WeissBladeworkPlus",
  SolarIsotoma = "SolarIsotoma",
  SolarIsotomaPlus = "SolarIsotomaPlus",
  // Amber
  Sharpshooter = "Sharpshooter",
  SharpshooterPlus = "SharpshooterPlus",
  ExplosivePuppet = "ExplosivePuppet",
  ExplosivePuppetPlus = "ExplosivePuppetPlus",
  // Barbara
  WhisperOfWater = "WhisperOfWater",
  WhisperOfWaterPlus = "WhisperOfWaterPlus",
  LetTheShowBegin = "LetTheShowBegin",
  LetTheShowBeginPlus = "LetTheShowBeginPlus",
  // Beidou
  Oceanborn = "Oceanborn",
  OceanbornPlus = "OceanbornPlus",
  Tidecaller = "Tidecaller",
  TidecallerPlus = "TidecallerPlus",
  // Bennett
  StrikeOfFortune = "StrikeOfFortune",
  StrikeOfFortunePlus = "StrikeOfFortunePlus",
  PassionOverload = "PassionOverload",
  PassionOverloadPlus = "PassionOverloadPlus",
  // ChongYun
  LayeredFrost = "LayeredFrost",
  LayeredFrostPlus = "LayeredFrostPlus",
  Demonbane = "Demonbane",
  DemonbanePlus = "DemonbanePlus",
  // Diluc
  SearingOnslaught = "SearingOnslaught",
  SearingOnslaughtPlus = "SearingOnslaughtPlus",
  TemperedSword = "TemperedSword",
  TemperedSwordPlus = "TemperedSwordPlus",
  // Diona
  KatzleinStyle = "KatzleinStyle",
  KatzleinStylePlus = "KatzleinStylePlus",
  IcyPaws = "IcyPaws",
  IcyPawsPlus = "IcyPawsPlus",
  // Eula
  IcetideVortex = "IcetideVortex",
  IcetideVortexPlus = "IcetideVortexPlus",
  EdelBladework = "EdelBladework",
  EdelBladeworkPlus = "EdelBladeworkPlus",
  // Fischl
  BoltsOfDownfall = "BoltsOfDownfall",
  BoltsOfDownfallPlus = "BoltsOfDownfallPlus",
  Nightrider = "Nightrider",
  NightriderPlus = "NightriderPlus",
  // Ganyu
  LiutianArchery = "LiutianArchery",
  LiutianArcheryPlus = "LiutianArcheryPlus",
  TrailOfTheQilin = "TrailOfTheQilin",
  TrailOfTheQilinPlus = "TrailOfTheQilinPlus",
  // HuTao
  GuideOfAfterlife = "GuideOfAfterlife",
  GuideOfAfterlifePlus = "GuideOfAfterlifePlus",
  SpearOfWangsheng = "SpearOfWangsheng",
  SpearOfWangshengPlus = "SpearOfWangshengPlus",
  // Jean
  FavoniusBladework = "FavoniusBladework",
  FavoniusBladeworkPlus = "FavoniusBladeworkPlus",
  GaleBlade = "GaleBlade",
  GaleBladePlus = "GaleBladePlus",
  // Kaeya
  CeremonialBladework = "CeremonialBladework",
  CeremonialBladeworkPlus = "CeremonialBladeworkPlus",
  Frostgnaw = "Frostgnaw",
  FrostgnawPlus = "FrostgnawPlus",
  // Kazuha
  Chihayaburu = "Chihayaburu",
  ChihayaburuPlus = "ChihayaburuPlus",
  GaryuuBladework = "GaryuuBladework",
  GaryuuBladeworkPlus = "GaryuuBladeworkPlus",
  // KeQing
  StellarRestoration = "StellarRestoration",
  StellarRestorationPlus = "StellarRestorationPlus",
  YunlaiSwordsmanship = "YunlaiSwordsmanship",
  YunlaiSwordsmanshipPlus = "YunlaiSwordsmanshipPlus",
  // Klee
  Kaboom = "Kaboom",
  KaboomPlus = "KaboomPlus",
  JumpyDumpty = "JumpyDumpty",
  JumpyDumptyPlus = "JumpyDumptyPlus",
  // Lisa
  LightningTouch = "LightningTouch",
  LightningTouchPlus = "LightningTouchPlus",
  VioletArc = "VioletArc",
  VioletArcPlus = "VioletArcPlus",
  // Lumine
  ForeignIronwind = "ForeignIronwind",
  ForeignIronwindPlus = "ForeignIronwindPlus",
  PalmVortex = "PalmVortex",
  PalmVortexPlus = "PalmVortexPlus",
  // Mona
  MirrorReflections = "MirrorReflections",
  MirrorReflectionsPlus = "MirrorReflectionsPlus",
  RippleOfFate = "RippleOfFate",
  RippleOfFatePlus = "RippleOfFatePlus",
  // NingGuang
  JadeScreen = "JadeScreen",
  JadeScreenPlus = "JadeScreenPlus",
  SparklingScatter = "SparklingScatter",
  SparklingScatterPlus = "SparklingScatterPlus",
  // Noelle
  Breastplate = "Breastplate",
  BreastplatePlus = "BreastplatePlus",
  MaidsBladework = "MaidsBladework",
  MaidsBladeworkPlus = "MaidsBladeworkPlus",
  // QiQi
  AncientSwordArt = "AncientSwordArt",
  AncientSwordArtPlus = "AncientSwordArtPlus",
  HeraldOfFrost = "HeraldOfFrost",
  HeraldOfFrostPlus = "HeraldOfFrostPlus",
  // Raiden
  BalefulOmen = "BalefulOmen",
  BalefulOmenPlus = "BalefulOmenPlus",
  Origin = "Origin",
  OriginPlus = "OriginPlus",
  // Razor
  ClawAndThunder = "ClawAndThunder",
  ClawAndThunderPlus = "ClawAndThunderPlus",
  SteelFang = "SteelFang",
  SteelFangPlus = "SteelFangPlus",
  // Rosaria
  RavagingConfession = "RavagingConfession",
  RavagingConfessionPlus = "RavagingConfessionPlus",
  SpearOfTheChurch = "SpearOfTheChurch",
  SpearOfTheChurchPlus = "SpearOfTheChurchPlus",
  // Sucrose
  AnemoHypostatis = "AnemoHypostatis",
  AnemoHypostatisPlus = "AnemoHypostatisPlus",
  WindSpiritCreation = "WindSpiritCreation",
  WindSpiritCreationPlus = "WindSpiritCreationPlus",
  // Tartaglia
  CuttingTorrent = "CuttingTorrent",
  CuttingTorrentPlus = "CuttingTorrentPlus",
  RagingTide = "RagingTide",
  RagingTidePlus = "RagingTidePlus",
  // Venti
  DivineArchery = "DivineArchery",
  DivineArcheryPlus = "DivineArcheryPlus",
  SkywardSonnet = "SkywardSonnet",
  SkywardSonnetPlus = "SkywardSonnetPlus",
  // XiangLing
  DoughFu = "DoughFu",
  DoughFuPlus = "DoughFuPlus",
  GuobaFire = "GuobaFire",
  GuobaFirePlus = "GuobaFirePlus",
  // Xiao
  LemniscaticWind = "LemniscaticWind",
  LemniscaticWindPlus = "LemniscaticWindPlus",
  WhirlwindThrust = "WhirlwindThrust",
  WhirlwindThrustPlus = "WhirlwindThrustPlus",
  // XingQiu
  GuhuaStyle = "GuhuaStyle",
  GuhuaStylePlus = "GuhuaStylePlus",
  FatalRainscreen = "FatalRainscreen",
  FatalRainscreenPlus = "FatalRainscreenPlus",
  // Xinyan
  DanceOfFire = "DanceOfFire",
  DanceOfFirePlus = "DanceOfFirePlus",
  SweepingFervor = "SweepingFervor",
  SweepingFervorPlus = "SweepingFervorPlus",
  // Yanfei
  SealOfApproval = "SealOfApproval",
  SealOfApprovalPlus = "SealOfApprovalPlus",
  SignedEdict = "SignedEdict",
  SignedEdictPlus = "SignedEdictPlus",
  // Yoimiya
  FireworkFlareUp = "FireworkFlareUp",
  FireworkFlareUpPlus = "FireworkFlareUpPlus",
  NiwabiFireDance = "NiwabiFireDance",
  NiwabiFireDancePlus = "NiwabiFireDancePlus",
  // ZhongLi
  DominusLapidis = "DominusLapidis",
  DominusLapidisPlus = "DominusLapidisPlus",
  RainOfStone = "RainOfStone",
  RainOfStonePlus = "RainOfStonePlus",
  // misc
  Burn = "Burn",
  Dash = "Dash",
  Freeze = "Freeze",
  Overheat = "Overheat",
}

export enum EPlayerEffect {
  Breastplate = "Breastplate",
  DominusLapidis = "DominusLapidis",
  ExplosivePuppet = "ExplosivePuppet",
  GlacialIllumination = "GlacialIllumination",
  GuideOfAfterlife = "GuideOfAfterlife",
  GuobaFire = "GuobaFire",
  LayeredFrost = "LayeredFrost",
  LetTheShowBeginPlus = "LetTheShowBeginPlus",
  MirrorReflections = "MirrorReflections",
  NiwabiFireDance = "NiwabiFireDance",
  Overheat = "Overheat",
  Pyronado = "Pyronado",
  Raincutter = "Raincutter",
  SkywardSonnet = "SkywardSonnet",
  SkywardSonnetPlus = "SkywardSonnetPlus",
  SolarIsotoma = "SolarIsotoma",
  Stormbreaker = "Stormbreaker",
  TrailOfTheQilin = "TrailOfTheQilin",
}

export enum EEnemyEffect {
  Nightrider = "Nightrider",
  NightriderPlus = "NightriderPlus",
}

export enum EEnemy {
  // normal
  AnemoBoxer = "AnemoBoxer",
  AnemoShamachurl = "AnemoShamachurl",
  CryoAbyssMage = "CryoAbyssMage",
  CryoCicinSwarm = "CryoCicinSwarm",
  CryoGunner = "CryoGunner",
  CryoHilichurlShooter = "CryoHilichurlShooter",
  CryoWhopperflower = "CryoWhopperflower",
  DendroShamachurl = "DendroShamachurl",
  ElectroCicinSwarm = "ElectroCicinSwarm",
  ElectroHammer = "ElectroHammer",
  ElectroHilichurlShooter = "ElectroHilichurlShooter",
  GeoChanter = "GeoChanter",
  GeoShamachurl = "GeoShamachurl",
  GiantAnemoSlime = "GiantAnemoSlime",
  GiantCryoSlime = "GiantCryoSlime",
  GiantDendroSlime = "GiantDendroSlime",
  GiantElectroSlime = "GiantElectroSlime",
  GiantGeoSlime = "GiantGeoSlime",
  GiantHydroSlime = "GiantHydroSlime",
  GiantPyroSlime = "GiantPyroSlime",
  HilichurlBerserk = "HilichurlBerserk",
  HilichurlGang = "HilichurlGang",
  HilichurlGrenadier = "HilichurlGrenadier",
  HilichurlGuard = "HilichurlGuard",
  HydroAbyssMage = "HydroAbyssMage",
  HydroGunner = "HydroGunner",
  PyroAbyssMage = "PyroAbyssMage",
  PyroHilichurlShooter = "PyroHilichurlShooter",
  PyroSlinger = "PyroSlinger",
  PyroWhopperflower = "PyroWhopperflower",
  SmallAnemoSlime = "SmallAnemoSlime",
  SmallCryoSlime = "SmallCryoSlime",
  SmallDendroSlime = "SmallDendroSlime",
  SmallElectroSlime = "SmallElectroSlime",
  SmallGeoSlime = "SmallGeoSlime",
  SmallHydroSlime = "SmallHydroSlime",
  SmallPyroSlime = "SmallPyroSlime",
  TreasureHoarderGang = "TreasureHoarderGang",
  UnusualHilichurl = "UnusualHilichurl",
  VishapHatchling = "VishapHatchling",
  // elite
  AnemoHypostasis = "AnemoHypostasis",
  BlazingAxeMitachurl = "BlazingAxeMitachurl",
  CicinCryoMage = "CicinCryoMage",
  CicinElectroMage = "CicinElectroMage",
  CryoRegisvine = "CryoRegisvine",
  ElectroHypostasis = "ElectroHypostasis",
  EyeOfStorm = "EyeOfStorm",
  FrostarmLawachurl = "FrostarmLawachurl",
  GeoHypostasis = "GeoHypostasis",
  PyroAgent = "PyroAgent",
  PyroRegisvine = "PyroRegisvine",
  RuinGrader = "RuinGrader",
  RuinGuard = "RuinGuard",
  RuinHunter = "RuinHunter",
  ShieldBearerMitachurl = "ShieldBearerMitachurl",
  StonehideLawachurl = "StonehideLawachurl",
}

export enum ELeyline {
  Adrenaline = "Adrenaline",
  ChaosCluster = "ChaosCluster",
  CondensedIce = "CondensedIce",
  ElementalRefresh = "ElementalRefresh",
  EnergyTides = "EnergyTides",
  EngulfingStorm = "EngulfingStorm",
  HighEnergyCores = "HighEnergyCores",
  IcicleBlast = "IcicleBlast",
  LightingBolts = "LightingBolts",
  MonsterAttendants = "MonsterAttendants",
  PlasmaField = "PlasmaField",
  ReinforcedShields = "ReinforcedShields",
  SheerCold = "SheerCold",
  SlowingWater = "SlowingWater",
  SmolderingFlames = "SmolderingFlames",
  WindCurrent = "WindCurrent",
}

export enum EDetailedStep {
  AddCard = "AddCard",
  DiscardCard = "DiscardCard",
  DrawCards = "DrawCards",
  EnemyTakeDamage = "EnemyTakeDamage",
  EnemyBlockDamage = "EnemyBlockDamage",
  EnemyDeath = "EnemyDeath",
  EnemyAppearance = "EnemyAppearance",
  PlayerTakeDamage = "PlayerTakeDamage",
  PlayerHeal = "PlayerHeal",
  PlayerChangeEnergy = "PlayerChangeEnergy",
  PlayerChangeShield = "PlayerChangeShield",
  PlayerChangeMora = "PlayerChangeMora",
  PlayerChangeActionPoints = "PlayerChangeActionPoints",
  PlayerGetEffect = "PlayerGetEffect",
  PlayerLoseEffect = "PlayerLoseEffect",
  EnemyGetElement = "EnemyGetElement",
  EnemyReaction = "EnemyReaction",
  EnemyChangeShield = "EnemyChangeShield",
  EnemyHeal = "EnemyHeal",
  UpgradeCard = "UpgradeCard",
  EnergyFreezed = "EnergyFreezed",
  TrashCard = "TrashCard",
  UseLeyline = "UseLeyline",
  EffectTrigger = "EffectTrigger",
  EnemyAttack = "EnemyAttack",
  EnemyGetEffect = "EnemyGetEffect",
  EnemyLoseEffect = "EnemyLoseEffect",
  EnemyEffectTrigger = "EnemyEffectTrigger",
}
